# name: CR Stackspot AI

# on:
#   pull_request:
#     branches: [main]

# permissions:
#   issues: write
#   pull-requests: write
#   contents: read

# jobs:
#   code-review:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with: 
#           fetch-depth: 2
#       - uses: victorsilvazup/stackspot-ai-execute-rqc@v1
#         id: rqc
#         with:
#             CLIENT_ID: ${{ secrets.CLIENT_ID }}
#             CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
#             CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
#             QC_SLUG: cr-stackspot
#             FILE_EXTENSION: .tsx

#       - name: Create comment
#         uses: peter-evans/create-or-update-comment@v4
#         with:
#           issue-number: ${{ github.event.pull_request.number }}
#           body: ${{ steps.rqc.outputs.rqc_result }}
#           reactions: 'rocket'
